// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDamy8GJadwfTeX6epZaGy-h0wU-PIucvk',
    appId: '1:692030613513:android:0488382210a767a57070d8',
    messagingSenderId: '692030613513',
    projectId: 'grocerystore-32f0d',
    storageBucket: 'grocerystore-32f0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYvlEUDr8giWAeegf1efUS9ewRebt6auk',
    appId: '1:692030613513:ios:df8e5ec45d22e3807070d8',
    messagingSenderId: '692030613513',
    projectId: 'grocerystore-32f0d',
    storageBucket: 'grocerystore-32f0d.firebasestorage.app',
    iosBundleId: 'pk.daana.daana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA419bEtzO8BBi29voJ2VyQ29s5uDVQTK0',
    appId: '1:692030613513:web:8306467ac528001d7070d8',
    messagingSenderId: '692030613513',
    projectId: 'grocerystore-32f0d',
    authDomain: 'grocerystore-32f0d.firebaseapp.com',
    storageBucket: 'grocerystore-32f0d.firebasestorage.app',
    measurementId: 'G-DS8FK324E0',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA419bEtzO8BBi29voJ2VyQ29s5uDVQTK0',
    appId: '1:692030613513:web:8306467ac528001d7070d8',
    messagingSenderId: '692030613513',
    projectId: 'grocerystore-32f0d',
    authDomain: 'grocerystore-32f0d.firebaseapp.com',
    storageBucket: 'grocerystore-32f0d.firebasestorage.app',
    measurementId: 'G-DS8FK324E0',
  );

}